"""migrate payment

Revision ID: 945f97256b8a
Revises: b2c234dcaca1
Create Date: 2026-03-10 01:55:02.582220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945f97256b8a'
down_revision = 'b2c234dcaca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paystack_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gateway_response', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('channel', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('card_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last4', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('bank', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('authorization_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('access_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('paystack_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('reference',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('amount_ngn',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('currency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.alter_column('amount_ngn',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('reference',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('paystack_data')
        batch_op.drop_column('access_code')
        batch_op.drop_column('authorization_url')
        batch_op.drop_column('bank')
        batch_op.drop_column('last4')
        batch_op.drop_column('card_type')
        batch_op.drop_column('channel')
        batch_op.drop_column('gateway_response')
        batch_op.drop_column('paystack_status')

    # ### end Alembic commands ###
